

server:
  port : 8080
  servlet:
    context-path: /BookingService

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/BookingService"
    username : root
    password : root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
jwt:
  signerKey: "3aF+lAiyA/tEAeeBtmlou0RwdTwXx0lU6SjH0MYBR7DRt9vyJzlv66uqnqHMP2NW"